<a href="https://colab.research.google.com/github/sush2004/Python/blob/main/Array_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Print pyramid structure 

In [ ]:
for i in range(4):    # i can take value from 0 to 3
    for j in range(i+1): # j will start taking value from 1 to 4
     print(" # ", end = "")
     
    print()

 # 
 #  # 
 #  #  # 
 #  #  #  # 


Print inverse Pyramid Structure

In [ ]:
for i in range(4):
   for j in range(4-i):
     print("# ", end="")

   print()

# # # # 
# # # 
# # 
# 


Print number which is divisible by 6

In [ ]:
nums = [31, 336, 56, 11, 96]  

for i in nums:
  if i % 6 == 0:
    print("Number divisible by 6 is ", i)
    break
else:
   print("Not found")
        

Number divisible by 6 is  336


Program to check whether a number is Prime or not

In [ ]:
num = int(input("Enter the number"))  # taking user input
for i in range(2, num):            # running for  loop from 2 to num-19
  if num % i == 0:                
    print("The number is not prime")
    break
else:
   print("The number is prime")

Enter the number7
The number is prime


Program to print all Prime numbers in an Interval


In [ ]:
lower = 0
upper = 10
print("Prime number between", lower, "and", upper, "are:")
for num in range(lower, upper + 1):  # num can take value from 0 to 10
  if num > 1:                       # 0 and 1 eliminated that means 2 to 10.
    for i in range(2, num):           # i can take value from 2 to 9
        if (num % i) == 0:
          break
    else:       
        print(num)



Prime number between 0 and 10 are:
2
3
5
7


Print square of number using for loop in array

In [ ]:
vals = array('i', [4,8,7,8,9])

newArr = array(vals.typecode, (a*a for a in vals))

for e in newArr:
  print(e)

16
64
49
64
81


In [ ]:
vals = array('i', [4,8,7,8,9])
newArr = array(vals.typecode, (a*a for a in vals))
i = 0
while i < len(newArr):
  print(newArr[i])
  i+=1

16
64
49
64
81


Enter value in array and then search the index value of element of the array.

In [ ]:
arr = array('i', [])                            #declaring array
n = int(input("Enter the length of the array"))               # taking input from user
for i in range(n):                              # using for inputting value.
  x = int(input("Enter the next value"))
  arr.append(x)

print(arr[0])           # printing value of array by fetching index

val = int(input("Enter the value you need to search"))  
k = 0                             #setting counter
for e in arr:                     
  if e== val:
    print(k)
    
  k+=1

  #print(arr.index(val))

Enter the length of the array5
Enter the next value44
Enter the next value99
Enter the next value44
Enter the next value66
Enter the next value88
44
Enter the value you need to search44
0
2


Concatenate two arrays

In [ ]:
from numpy import *
arr1 = array([1, 2, 4, 6, 7])
arr2 = array([2, 5,6, 3, 6])
print(concatenate([arr1, arr2]))

[1 2 4 6 7 2 5 6 3 6]


In [ ]:
arr1 = array([
              [1,2,3,2,9,10],
              [4,5,6,33,8,4]
              ])
print(arr1.ndim)     # tells the dimension 
print(arr1.shape)     # tells the structure of the array.
print(arr1.size)      # tell the size
arr2 = arr1.flatten()
print(arr2)

arr3 = arr2.reshape(2,2,3)
print(arr3)

2
(2, 6)
12
[ 1  2  3  2  9 10  4  5  6 33  8  4]
[[[ 1  2  3]
  [ 2  9 10]]

 [[ 4  5  6]
  [33  8  4]]]


NameError: ignored